from sqlalchemy import Column, String, Integer, DateTime, JSON, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime, timezone
import uuid

from app.database import Base

class JobLog(Base):
    """Tracking model for webhook inputs and outputs (Acompanhamento)"""
    __tablename__ = "job_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(String(255), nullable=True, index=True) # ID from queue if async, or custom ID
    webhook_path = Column(String(255), nullable=False, index=True) # endpoint hit
    status = Column(String(50), default="queued", nullable=False) # queued, in_progress, completed, failed
    
    # Payload details
    request_data = Column(JSON, nullable=True) # Input payload sent to system
    response_data = Column(JSON, nullable=True) # Output generated by the agent/system
    error_message = Column(String, nullable=True) # Contains stack trace or error if failed
    
    # Timing
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    completed_at = Column(DateTime(timezone=True), nullable=True)
    duration_ms = Column(Integer, nullable=True)

    def __repr__(self):
        return f"<JobLog {self.id} | path={self.webhook_path} | status={self.status}>"
